config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'pages#index'

  get '/tutor_signup', to: 'pages#tutor_signup'
  get '/find_a_tutor', to: 'pages#find_a_tutor'
  get '/edit-profile', to: 'pages#tutor_profile'
  patch '/edit-profile', to: 'pages#update_profile'
  get '/edit-skills', to: 'pages#skills_profile'
  post 'tutor/skill', to: 'tutors#add_skill'
  get 'profile', to: 'pages#show'
  get 'profile/:id', to: 'pages#show'

  get 'facebook', to: 'pages#facebook'

  resources :charges, only: [:new, :create]

  resources :tutors

  get 'upgrades/create'
  resources :upgrades

  resources :conversations do
    resources :messages
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
 belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
 belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

 has_many :messages, dependent: :destroy
 validates_uniqueness_of :sender_id, :scope => :recipient_id
 scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end
end

app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end
end

app/models/skill.rb
class Skill < ApplicationRecord

end

app/models/tutor.rb
class Tutor < ApplicationRecord
  belongs_to :user
  has_many :tutor_skills
  has_many :skills, through: :tutor_skills
  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/tutor_skill.rb
class TutorSkill < ApplicationRecord
  belongs_to :skill
  validates_uniqueness_of :skill_id, :scope => :tutor_id
end

app/models/user.rb
class User < ApplicationRecord
  has_one :tutor
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :location  # can also be an IP address
  after_validation :geocode # auto-fetch coordinates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :role])
 end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 200

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    current_user.tutor.upgrade = true
    current_user.tutor.save

    UpgradeMailer.upgrade_success(current_user).deliver_now

    puts charge.inspect


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
 before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
    @over_ten = true
    @messages = @messages[-10..-1]
  end

  if params[:m]
   @over_ten = false
   @messages = @conversation.messages
  end
 if @messages.last
  if @messages.last.user_id != current_user.id
   @messages.last.read = true;
  end
 end
@message = @conversation.messages.new
 end
def new
 @message = @conversation.messages.new
end
def create
 @message = @conversation.messages.new(message_params)
 if @message.save
  redirect_to conversation_messages_path(@conversation)
 end
end
private
 def message_params
  params.require(:message).permit(:body, :user_id)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:tutor_profile]

  def index
  end

  def tutor_signup
  end

  def find_a_tutor
    @tutors = Tutor.order(:upgrade)
    @map_tutors = []
    User.where(role: "tutor").each do |user|
      puts user.inspect
      skills = []
      if !user.tutor.nil?
        user.tutor.skills.each do |skill|
          skills.push(skill.name)
        end

        if !user.latitude.nil?
          @map_tutors.push({
            latitude:user.latitude,
            longitude:user.longitude,
            name:user.name,
            headline:user.tutor.headline,
            skills:skills,
            hourly_rate: user.tutor.hourly_rate,
            avatar:user.tutor.avatar.url(:thumb),
            id:user.id,
          })
        end
      end
    end
  end

  def skills_profile
    @skills = current_user.tutor.skills
  end


  def show
    if params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    puts @user.inspect
    @skills = @user.tutor.skills
    @headline = @user.tutor.headline
    @description = @user.tutor.description
    @hourly_rate = @user.tutor.hourly_rate
    @image = @user.tutor.avatar.url(:medium)
  end


  def tutor_profile

    if current_user.tutor.nil?
      Tutor.create({user:current_user})
    end
    @tutor = current_user.tutor

  end




  def update_profile
    @profile = current_user.tutor
    @profile.headline = params[:tutor][:headline]
    @profile.description = params[:tutor][:description]
    @profile.hourly_rate = params[:tutor][:hourly_rate]
    @profile.avatar = params[:tutor][:avatar]
    @profile.save
    redirect_to "/edit-skills"
  end

  def facebook
  end

end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController

  def add_skill
    @skill = TutorSkill.new
    @skill.tutor_id = current_user.tutor.id
    @skill.skill_id = params[:skill_id]
    @skill.save
    redirect_to "/edit-skills"
  end

  def index
    @tutors = User.where("location= ?",  params[:search])
  end
  

end

app/controllers/upgrades_controller.rb
class UpgradesController < ApplicationController
  def create
    upgarde = Upgrade.new(upgrade_params)
    if upgrade.save
    redirect_to '/', notice: "Thanks for upgrading!"
  else
    redirect_to '/', notice: { errors: upgrade.errors}
  end

  end

  private

  def upgrade_params
    params.require(:upgrade).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/admin/dashboard/_search_user.html.erb
  <div class="panel_contents">
  <form method="get" id="q_search" class="filter_form" action="/admin/users" accept-charset="UTF-8">
    <div class="filter_form_field filter_string">
      <label for="q_location" class=" label">Search location:</label>
      <input type="text" name="q[location_contains]" id="q_location" size="30"/>
      <input type="submit" value="Go" name="commit" id="q_submit" />
    </div>
  </form>
</div>

<div class="panel_contents">
  <form method="get" id="q_search" class="filter_form" action="/admin/skills" accept-charset="UTF-8">
    <div class="filter_form_field filter_string">
      <label for="q_skill" class=" label">Search skill:</label>
      <input type="text" name="q[name_contains]" id="q_skill" size="30"/>
      <input type="submit" value="Go" name="commit" id="q_submit" />
    </div>
  </form>
</div>

app/views/charges/create.html.erb
<div class="container-fluid">
  <h1>Thankyou for your payment!</h1><br>

  <h3><%= link_to "Continue to your profile", '/profile' %></h3>
</div>

app/views/charges/new.html.erb
<h1>What is a Bump Up?</h1>

<h3>It’s simply paying a little money to get your ad – regular or featured –
  back to the top of the listings. </h3>

<%= form_with url: charges_path, local: true do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $2.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Bump up your profile"
          data-amount="200"
          data-locale="auto"></script>
<% end %>

app/views/conversations/index.html.erb
<div class="ui segment">
 <h3>Mailbox</h3>
 <div class="ui list">
  <div class="item">
   <% @conversations.each do |conversation| %>
   <% if conversation.sender_id == current_user.id ||      conversation.recipient_id == current_user.id %>
    <% if conversation.sender_id == current_user.id %>
      <% recipient = User.find(conversation.recipient_id) %>
    <% else %>
      <% recipient = User.find(conversation.sender_id) %>
    <% end %>
    <%= link_to recipient.name,   conversation_messages_path(conversation)%>
   <% end %>
  <% end %>
  </div>
 </div>
</div>
<div class="ui segment">
 <h3>All Users</h3>
  <div class="ui list">
   <% @users.each do |user| %>
    <% if user.id != current_user.id %>
     <div class="item">
   <%= user.name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
 </div>
  <% end %>
 <% end %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clevercat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

  </head>

  <body>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:600,300' rel='stylesheet' type='text/css'>


      		<nav id="navigation" class="nav" role="navigation" onclick="">
    			<ul>
    				<li class="current"><a href="/"><%= image_tag "CleverCat(2).png", size: "80x80" %></a></li>
    				<li><a href="/find_a_tutor">Find a Tutor</a></li>
    				<li><a href="/tutor_signup">Start Tutoring</a></li>
            <li><a href="/conversations">Mail Box</a></li>

          <span class="navbar-text">
            <% if !user_signed_in? %>
              <%= link_to "Log in", new_user_session_path %>
            <% end %>

            <% if user_signed_in? %>
              Welcome, <%= current_user.email %> | <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% end %>
            </ul>
          </span>
    		</nav>


    <%= yield %>



  </body>
</html>

app/views/messages/index.html.erb
<div class="container">
  <%= link_to 'Back', conversations_path, class: "btn btn-primary" %>
  <h3>Begin Message With
  <%= @conversation.sender.name %>
  and
  <%= @conversation.recipient.name %></h3>
  <% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>
<div class="ui segment">
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class="item">
    <div class="content">
     <div class="header"><strong><%= user.name %></strong>     <%= message.message_time %></div>
      <div class="list">
       <div class="item">
        <i class="right triangle icon"></i>
         <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>
<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
 <div class="field">
   <%= f.text_area :body, class: "form-control" %>
 </div>
 <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
 <div>
   <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
 </div>
<% end %>

app/views/pages/facebook.html.erb
<script>

  function checkLoginState() {
    console.log('checkLoginState');
    FB.getLoginStatus(function(response) {
      console.log(response);
      if (response.status === 'connected') {
        console.log('Logged in');
        var button = document.getElementById('fb-login-button');
        var review = document.getElementById('review');
        button.style.display = 'none';
        review.style.display = 'block';
        // window.location = '/ratings';
      } else {
        console.log('Not logged in');
      }
    });
  }

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1948918882013182',
      cookie     : true,
      xfbml      : true,
      version    : 'v1.0'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

   window.addEventListener("load", function() {
     setTimeout(checkLoginState, 200);
   });
</script>


<fb:login-button
  id="fb-login-button"
  scope="public_profile,email"
  onlogin="checkLoginState();">
</fb:login-button>

<div id="review" style="display:none">
  <label>Enter your review</label>
  <input type="text"></input>
</div>

app/views/pages/find_a_tutor.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

</div>
Enter your location
      <%= form_tag(tutors_path, method: 'get') do %>
      <%= text_field_tag(:search, params[:search]) %>
       <%= submit_tag("Search", location: nil) %>
<% end %>
  <p class="landingbutton">
    <label for="postcode">Find tutors near you. Please enter your postcode</label>
    <input name="postcode" type="text" id="postcode"></input>
       </p>
</div>

<div id="map"></div>
<script>
var locations = <%= @map_tutors.to_json.html_safe %>;
  // var locations = []
  var gMap;
  function initMap() {
    var mapSetup = {
      zoom: 11,
      center: {
        lat: 9.9312,
        lng: 76.2673
      }
    };

    //If a postcode has been searched before, use that on load
    if (localStorage) {
      var lastSearchString = localStorage.getItem('lastSearch');
      if (lastSearchString) {
        var lastSearch = JSON.parse(lastSearchString);
        if (lastSearch) {
          mapSetup.zoom = 10;
          mapSetup.center = lastSearch;
        }
      }

    };

    gMap = new google.maps.Map(document.getElementById('map'), mapSetup);
    var infowindows = [];

    function markerClicked(marker) {
      return function () {
        var contentString = '<div id="content"><div id="siteNotice"></div><h4 id="firstHeading" class="firstHeading">' + marker.location.name +
        '</h4>' +
        '<div id="bodyContent"><b>Headline:</b> ' + marker.location.headline +
        '<div id="bodyContent"><b>Skills:</b> ' + marker.location.skills.join(", ") +
        '<div id="bodyContent"><b>Hourly Rate $:</b> ' + marker.location.hourly_rate +
        '<div id="bodyContent"><img src="' + marker.location.avatar+ '">' +
        ', <br><a href="/profile/' + marker.location.id + '">'+
        ' Contact this tutor</a>'

        '.</div></div>';

        // https://developers.google.com/maps/documentation/javascript/infowindows#close
        var infowindow = new google.maps.InfoWindow({content: contentString});
        infowindow.open(gMap, marker);
        infowindows.forEach(function (w) {
          w.close()
        });
        infowindows.push(infowindow);
      }
    }

    // var markers = locations.map(function (location, i) {
    //   // https://developers.google.com/maps/documentation/javascript/markers
    //   var marker = new google.maps.Marker({map: gMap, position: location.coords, });
    //   marker.location = location;
    //   marker.addListener('click', markerClicked(marker));
    //   return marker;
    // });
    // // remove the above once this one approved
    var markers = locations.map(function (location, i) {
      // https://developers.google.com/maps/documentation/javascript/markers
      var marker = new google.maps.Marker({
        map: gMap,
        position: {
          lat: location.latitude,
          lng: location.longitude
        }
      });
      marker.location = location;
      marker.addListener('click', markerClicked(marker));
      return marker;
    });

    // Add a marker clusterer to manage the markers.
    var markerCluster = new MarkerClusterer(gMap, markers, {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
  }

  var postcodeInput = document.getElementById('postcode');
  postcodeInput.oninput = function () {
    if (postcodeInput.value.length !== 4)
      return;

    var url = 'https://maps.googleapis.com/maps/api/geocode/json?address=' + postcodeInput.value + ',+Australia&key=AIzaSyBe6vvbBBOqwBOPODr-W30BHPn_gdRfBnU';
    var oReq = new XMLHttpRequest();
    oReq.addEventListener("load", function () {
      var data = JSON.parse(this.responseText);
      if (data.status !== 'OK')
        return;
      if (!data.results[0])
        return;
      var location = data.results[0].geometry.location;

      gMap.setCenter(location);
      gMap.setZoom(10);

      if (!localStorage)
        return;
      localStorage.setItem('lastSearch', JSON.stringify(location));
    });
    oReq.open("GET", url);
    oReq.send();
  }
  postcodeInput.onpropertychange = postcodeInput.oninput; // for IE8
</script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBe6vvbBBOqwBOPODr-W30BHPn_gdRfBnU&callback=initMap"></script>


  <% @tutors.each do |tutor| %>
    <div class="row listing">
      <div class="col-md-2 listing-photo"><br>
        <%= image_tag tutor.avatar.url(:thumb) %><br>
      </div>
      <div class="col-md-10 listing-text">
    <strong>Profile Headline:</strong>
    <p> <%= tutor.headline %> </p>
    <strong>Description:</strong>
    <p> <%= tutor.description %></p>
    <strong>Hourly Rate $: </strong>
    <p> <%= tutor.hourly_rate %> </p>
    <strong>Skills: </strong>
    <% tutor.skills.each do |skill| %>
    <%= skill.name %>
  <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/pages/index.html.erb
<div class="background_image">

  <div class="box">
    <h1><strong>Find Best Home Tutors in Kochi </strong></h1><br>
    <h3>We have 30,000+ qualified home tuition teachers to work with students. Search for the home tutor in your local area and get one to one free trial session.</h3><br>
    <h2> <a href="/find_a_tutor/" class="btn btn-primary"> Find a tutor now!</a></h2>

    <br>
  </div>

</div>

app/views/pages/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <% if user_signed_in? and @user.tutor == current_user.tutor %>
  <h6><%= link_to 'Do you need to Edit Your Profile?', "/edit-profile" %></h6><br>
  <% end %>

  <p><strong>Profile Avatar:</strong></p>
  <%= image_tag @image%>


  <p>
    <strong>Profile Headline:</strong>
    <%= @headline %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @description %>
  </p>

  <p>
    <strong>Hourly Rate: </strong>
    <%= @hourly_rate %>
  </p>

  <p>
    <strong>Skills: </strong><br>
    <% @skills.each do |skill| %>
    <%= skill.name %>

    <% end %>  </p>

    <% if user_signed_in? %>
      <%= link_to t(".contact", :default => t("helpers.links.contact_tutor")), conversations_path(sender_id: current_user.id, recipient_id: @user.id), :method => 'post', :class => 'btn btn-primary' %>
    <% end %>

    <% if user_signed_in? and @user.tutor == current_user.tutor %>
      <h6><%= link_to 'Do you want to Bump Up Your Profile', "/charges/new"%></h6><br>
    <% end %>



</div>

app/views/pages/skills_profile.html.erb
<%= form_with model: @skill, local: true, url: "/tutor/skill" do |f| %>

<br>
<div class="field">
  <strong><%= f.label :skills %></strong><br>
  <%= f.collection_select(:skill_id, Skill.all, :id, :name) %><br>
</div>

<br>
<div class="actions">
<strong><%= f.label "Save Each Skill" %></strong><br>
  <%= f.submit class: 'btn btn-primary' %>
</div>

<% end %>
<% @skills.each do |skill| %>
<%= skill.name %><br>

<% end %>
<br>
<br><%= link_to "Finished Updating All My Skills!", profile_path %>

app/views/pages/tutor_profile.html.erb
<%= form_with model: @tutor, local: true, url: "/edit-profile", html: { multipart: true } do |f| %>


<br>
<div class="field">
  <strong><%= f.label 'profile headline' %></strong><br>
  <%= f.text_area :headline, :rows => 2, style: 'width:100%;' %>
</div>

<div class="field">
  <strong><%= f.label :description %></strong><br>
  <%= f.text_area :description, id: :description, :rows => 15, style: 'width:100%;' %>
</div>

<div class="field">
  <strong><%= f.label :hourly_rate, "Hourly Rate ($)" %></strong><br>
  <%= f.text_field :hourly_rate %>
</div>
<br>

<br>
<div class="field">
  <strong><%= f.label "Upload Profle Photo" %></strong><br>
  <%= f.file_field :avatar %><br>
</div>
<br>

<div class="actions">
  <%= f.submit class: 'btn btn-primary' %><br>
</div>

<% end %>

app/views/pages/tutor_signup.html.erb
    <div class="sign_up">
            <div class="text">
            <h1> You Want To Teach ?</h1><br>
            <h3>  Earn money by tutoring </h3><br>
            <h2> <a href="/edit-profile/" class="btn btn-primary"> Sign up as a tutor now!</a></h2>
        </div>
    </div>

app/views/tutors/index.html.erb
<div>
	<style>
table, th, td {
    border: 1px solid black;
}
</style>
	<table><tr>
		    <th>Name</th>
		    <th>class</th>
		    <th>location</th>
		  </tr>
		  <% @tutors.each do |tutors| %> 
<tr>
		  <td>
		  	<%= tutors.name%>
		  </td>
		  <td><%= tutors.email %></td>
	
	  <td><%=tutors.location  %></td>
	</tr>
<% end %>   
    </table>
</div>